### ISSUE TITLE
Mockup Feedback

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-midknight#2]
Among all groups, you are the only one that provide a link instead of a screenshot. This is unacceptable and an irresponsible act. I'm giving 2 demerit points to all members of this group.

**Comment by SLValerio** [comment]
sorry for the misunderstanding sir, but I have sent a link instead of a screenshot/s for our mock up so that you can be able to experience the navigation / clicking buttons of the mock up of our project.

**Comment by SLValerio** [comment]
but for obedience to the issue, let us upload the screenshots also of our mock up, thank you sir!

**Comment by ssvillarosa** [comment]
Hi Mr. Valerio,

I appreciate your compliance! I also understand that you have good intentions when you pasted that link. However, as sincere as you can be, pasting just the link without the actual screenshots is still unacceptable. If you intend it so I can navigate the mock up, you could've import the mock ups, say in a pdf file, then put the link there in case I want to navigate the actual mock up in Figma.

Other than that, I also notice your actions especially in ELEC1 was so different from your usual behavior. I understand that you have a lot on your plate and it might affect your mental health. I suggest that you take a rest maybe at least 3 days so you will get freshen up when you get back. For this sprint, you can designate someone to take over for the PM role. You have to trust your teammates and give them accountability for their tasks.

**Comment by SLValerio** [comment]
Thank you so much for your concern and understanding, Sir. After some consideration, I've decided to follow your suggestion. I'd like to grant authority to Mr. Villaruel as the temporary PM for our group during this sprint. Thanks again Sir and happy holidays!

**Comment by ssvillarosa** [comment]
Great! To make sure that all communications are clear, Mr. @aironvillaruel, please acknowledge this ticket and close.

**Comment by aironvillaruel** [comment]
As an interim PM, I will provide updates  to the upcoming sprint sir. Thank you for your patience and understanding.
